# Generated by Django 3.1.4 on 2021-01-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210128_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tagname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
